# Change these first
owner: krubkrong # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Krubkrong's Website
    url: https://krubkrong.com
  - name: Krubkrong's App
    url: https://app.krubkrong.com
  - name: Krubkrong's Api 
    url: https://api.krubkrong.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/87474215?s=200&v=4
  name: krubkrong
  introTitle: "**Krubkrong** provide an affordable stock and inventory management system to retailers and small business."
  introMessage: krubkrong Uppertime Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
